#############################################################################
# Makefile for building: rockbot
# Generated by qmake (3.1) (Qt 5.12.4)
# Project:  RockDroid.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile RockDroid.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc-7
CXX           = g++-7
DEFINES       = -DLINUX
CFLAGS        = -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++17 -O2 -DLINUX -DPC -Wno-reorder -Wno-ignored-qualifiers -Wno-deprecated -Wno-unused-parameter -Wno-sign-compare -fpermissive -mtune=generic -Werror=return-type -fstack-protector-all -fstack-protector -O2 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = rockbot1.0.0
DISTDIR = /home/ark/rockdroid/.tmp/rockbot1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib -lSDL_mixer -lSDL_image -lSDL_ttf -lSDL_gfx `sdl-config --libs` -ldl -lstdc++ -fstack-protector-all   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		aux_tools/fps_control.cpp \
		character/character.cpp \
		data/datautil.cpp \
		graphicslib.cpp \
		inputlib.cpp \
		game.cpp \
		logger.cpp \
		shareddata.cpp \
		stage.cpp \
		classmap.cpp \
		character/classplayer.cpp \
		timerlib.cpp \
		sceneslib.cpp \
		soundlib.cpp \
		projectilelib.cpp \
		character/classnpc.cpp \
		stage_select.cpp \
		class_config.cpp \
		objects/object.cpp \
		graphic/option_picker.cpp \
		scenes/dialogs.cpp \
		file/file_io.cpp \
		graphic/animation.cpp \
		character/artificial_inteligence.cpp \
		options/key_map.cpp \
		graphic/draw.cpp \
		aux_tools/trajectory_parabola.cpp \
		file/convert.cpp \
		character/movement/jump.cpp \
		character/movement/inertia.cpp \
		file/fio_scenes.cpp \
		scenes/sceneshow.cpp \
		strings_map.cpp \
		file/fio_strings.cpp \
		aux_tools/stringutils.cpp \
		file/fio_common.cpp \
		game_mediator.cpp \
		collision_detection.cpp \
		graphic/gfx_sin_wave.cpp \
		character/character_animation.cpp \
		aux_tools/exception_manager.cpp \
		scenes/game_menu.cpp \
		ports/android/android_game_services.cpp 
OBJECTS       = main.o \
		fps_control.o \
		character.o \
		datautil.o \
		graphicslib.o \
		inputlib.o \
		game.o \
		logger.o \
		shareddata.o \
		stage.o \
		classmap.o \
		classplayer.o \
		timerlib.o \
		sceneslib.o \
		soundlib.o \
		projectilelib.o \
		classnpc.o \
		stage_select.o \
		class_config.o \
		object.o \
		option_picker.o \
		dialogs.o \
		file_io.o \
		animation.o \
		artificial_inteligence.o \
		key_map.o \
		draw.o \
		trajectory_parabola.o \
		convert.o \
		jump.o \
		inertia.o \
		fio_scenes.o \
		sceneshow.o \
		strings_map.o \
		fio_strings.o \
		stringutils.o \
		fio_common.o \
		game_mediator.o \
		collision_detection.o \
		gfx_sin_wave.o \
		character_animation.o \
		exception_manager.o \
		game_menu.o \
		android_game_services.o
DIST          = AndroidAppSettings.cfg \
		docs/notes.txt \
		docs/Releases.txt \
		docs/crashes.txt \
		docs/translation_lines.txt \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		RockDroid.pro aux_tools/fps_control.h \
		character/character.h \
		data/datautil.h \
		file/v4/file_config_old.h \
		graphicslib.h \
		defines.h \
		inputlib.h \
		game.h \
		logger.h \
		shareddata.h \
		stage.h \
		classmap.h \
		character/classplayer.h \
		timerlib.h \
		sceneslib.h \
		soundlib.h \
		projectilelib.h \
		character/classnpc.h \
		stage_select.h \
		class_config.h \
		objects/object.h \
		graphic/option_picker.h \
		scenes/dialogs.h \
		file/format.h \
		file/file_io.h \
		graphic/animation.h \
		character/artificial_inteligence.h \
		character/st_spriteFrame.h \
		ports/ps2/modules.h \
		options/key_map.h \
		graphic/draw.h \
		aux_tools/trajectory_parabola.h \
		file/convert.h \
		file/format/st_characterState.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/format/st_platform.h \
		file/format/st_projectile.h \
		file/format/st_teleporter.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		file/version.h \
		file/fio_scenes.h \
		scenes/sceneshow.h \
		file/v4/file_config_v4.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_scene_v4.h \
		file/v4/file_stage_v4.h \
		strings_map.h \
		file/fio_strings.h \
		aux_tools/stringutils.h \
		file/v4/file_strings.h \
		file/v4/file_map.h \
		file/fio_common.h \
		game_mediator.h \
		file/v4/file_anim_block.h \
		collision_detection.h \
		graphic/gfx_sin_wave.h \
		character/character_animation.h \
		aux_tools/exception_manager.h \
		scenes/game_menu.h \
		ports/android/android_game_services.h main.cpp \
		aux_tools/fps_control.cpp \
		character/character.cpp \
		data/datautil.cpp \
		graphicslib.cpp \
		inputlib.cpp \
		game.cpp \
		logger.cpp \
		shareddata.cpp \
		stage.cpp \
		classmap.cpp \
		character/classplayer.cpp \
		timerlib.cpp \
		sceneslib.cpp \
		soundlib.cpp \
		projectilelib.cpp \
		character/classnpc.cpp \
		stage_select.cpp \
		class_config.cpp \
		objects/object.cpp \
		graphic/option_picker.cpp \
		scenes/dialogs.cpp \
		file/file_io.cpp \
		graphic/animation.cpp \
		character/artificial_inteligence.cpp \
		options/key_map.cpp \
		graphic/draw.cpp \
		aux_tools/trajectory_parabola.cpp \
		file/convert.cpp \
		character/movement/jump.cpp \
		character/movement/inertia.cpp \
		file/fio_scenes.cpp \
		scenes/sceneshow.cpp \
		strings_map.cpp \
		file/fio_strings.cpp \
		aux_tools/stringutils.cpp \
		file/fio_common.cpp \
		game_mediator.cpp \
		collision_detection.cpp \
		graphic/gfx_sin_wave.cpp \
		character/character_animation.cpp \
		aux_tools/exception_manager.cpp \
		scenes/game_menu.cpp \
		ports/android/android_game_services.cpp
QMAKE_TARGET  = rockbot
DESTDIR       = 
TARGET        = rockbot


first: all
####### Build rules

rockbot:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RockDroid.pro /usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		RockDroid.pro
	$(QMAKE) -o Makefile RockDroid.pro
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf:
RockDroid.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile RockDroid.pro

qmake_all: FORCE


all: Makefile rockbot

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp ports/android/android_game_services.h \
		defines.h \
		file/file_io.h \
		file/format.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		strings_map.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		aux_tools/stringutils.h \
		graphicslib.h \
		game_mediator.h \
		shareddata.h \
		objects/object.h \
		graphic/draw.h \
		soundlib.h \
		inputlib.h \
		timerlib.h \
		game.h \
		character/classplayer.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		scenes/game_menu.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		classmap.h \
		graphic/animation.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h \
		stage_select.h \
		ports/ps2/modules.h \
		ports/ps2/cdvd_rpc.h \
		ports/ps2/cdvd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

fps_control.o: aux_tools/fps_control.cpp aux_tools/fps_control.h \
		shareddata.h \
		defines.h \
		file/file_io.h \
		file/format.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		objects/object.h \
		graphicslib.h \
		game_mediator.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		timerlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fps_control.o aux_tools/fps_control.cpp

character.o: character/character.cpp character/character.h \
		file/format/st_hitPoints.h \
		file/format/st_common.h \
		defines.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		graphicslib.h \
		file/format.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		soundlib.h \
		timerlib.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		game.h \
		character/classplayer.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		classmap.h \
		graphic/animation.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h \
		inputlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o character.o character/character.cpp

datautil.o: data/datautil.cpp data/datautil.h \
		defines.h \
		file/format/st_common.h \
		file/v4/file_save_v4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datautil.o data/datautil.cpp

graphicslib.o: graphicslib.cpp defines.h \
		aux_tools/stringutils.h \
		inputlib.h \
		file/format.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		timerlib.h \
		soundlib.h \
		shareddata.h \
		file/file_io.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		objects/object.h \
		graphicslib.h \
		game_mediator.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		class_config.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classplayer.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		strings_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicslib.o graphicslib.cpp

inputlib.o: inputlib.cpp inputlib.h \
		defines.h \
		file/format.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		timerlib.h \
		game.h \
		character/classplayer.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		graphicslib.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		soundlib.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		classmap.h \
		graphic/animation.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputlib.o inputlib.cpp

game.o: game.cpp game.h \
		character/classplayer.h \
		character/character.h \
		file/format/st_hitPoints.h \
		file/format/st_common.h \
		defines.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		graphicslib.h \
		file/format.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		soundlib.h \
		timerlib.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		classmap.h \
		graphic/animation.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h \
		inputlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

logger.o: logger.cpp logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o logger.cpp

shareddata.o: shareddata.cpp shareddata.h \
		defines.h \
		file/file_io.h \
		file/format.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		objects/object.h \
		graphicslib.h \
		game_mediator.h \
		file/fio_strings.h \
		file/v4/file_strings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shareddata.o shareddata.cpp

stage.o: stage.cpp file/file_io.h \
		file/format.h \
		defines.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		stage.h \
		classmap.h \
		graphicslib.h \
		game_mediator.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		objects/object.h \
		character/classnpc.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		soundlib.h \
		timerlib.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/artificial_inteligence.h \
		graphic/animation.h \
		character/classplayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stage.o stage.cpp

classmap.o: classmap.cpp classmap.h \
		defines.h \
		file/format/st_common.h \
		graphicslib.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		character/classnpc.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		soundlib.h \
		timerlib.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/artificial_inteligence.h \
		graphic/animation.h \
		collision_detection.h \
		game.h \
		character/classplayer.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h \
		inputlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classmap.o classmap.cpp

classplayer.o: character/classplayer.cpp character/classplayer.h \
		character/character.h \
		file/format/st_hitPoints.h \
		file/format/st_common.h \
		defines.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		graphicslib.h \
		file/format.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		soundlib.h \
		timerlib.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		inputlib.h \
		class_config.h \
		game.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		classmap.h \
		graphic/animation.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classplayer.o character/classplayer.cpp

timerlib.o: timerlib.cpp timerlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timerlib.o timerlib.cpp

sceneslib.o: sceneslib.cpp sceneslib.h \
		defines.h \
		graphicslib.h \
		file/format/st_common.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		soundlib.h \
		inputlib.h \
		graphic/draw.h \
		graphic/gfx_sin_wave.h \
		stage_select.h \
		timerlib.h \
		file/version.h \
		graphic/animation.h \
		game.h \
		character/classplayer.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		stage.h \
		classmap.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h \
		ports/android/android_game_services.h \
		scenes/sceneshow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sceneslib.o sceneslib.cpp

soundlib.o: soundlib.cpp soundlib.h \
		defines.h \
		shareddata.h \
		file/file_io.h \
		file/format.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		objects/object.h \
		graphicslib.h \
		game_mediator.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		aux_tools/stringutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundlib.o soundlib.cpp

projectilelib.o: projectilelib.cpp projectilelib.h \
		file/format/st_common.h \
		defines.h \
		graphicslib.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		soundlib.h \
		timerlib.h \
		classmap.h \
		character/classnpc.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/artificial_inteligence.h \
		graphic/animation.h \
		collision_detection.h \
		game.h \
		character/classplayer.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectilelib.o projectilelib.cpp

classnpc.o: character/classnpc.cpp graphicslib.h \
		defines.h \
		file/format/st_common.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		stage.h \
		classmap.h \
		character/classnpc.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		soundlib.h \
		timerlib.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/artificial_inteligence.h \
		graphic/animation.h \
		character/classplayer.h \
		inputlib.h \
		game.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classnpc.o character/classnpc.cpp

stage_select.o: stage_select.cpp stage_select.h \
		graphicslib.h \
		defines.h \
		file/format/st_common.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		inputlib.h \
		timerlib.h \
		soundlib.h \
		aux_tools/stringutils.h \
		strings_map.h \
		graphic/draw.h \
		game.h \
		character/classplayer.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		scenes/game_menu.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		classmap.h \
		graphic/animation.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stage_select.o stage_select.cpp

class_config.o: class_config.cpp class_config.h \
		file/format/st_common.h \
		defines.h \
		character/character.h \
		file/format/st_hitPoints.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		graphicslib.h \
		file/format.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		soundlib.h \
		timerlib.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classplayer.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		inputlib.h \
		game.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		classmap.h \
		graphic/animation.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h \
		data/datautil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o class_config.o class_config.cpp

object.o: objects/object.cpp objects/object.h \
		graphicslib.h \
		defines.h \
		file/format/st_common.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		classmap.h \
		character/classnpc.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		soundlib.h \
		timerlib.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/artificial_inteligence.h \
		graphic/animation.h \
		game.h \
		character/classplayer.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o objects/object.cpp

option_picker.o: graphic/option_picker.cpp graphic/option_picker.h \
		file/format/st_common.h \
		defines.h \
		soundlib.h \
		shareddata.h \
		file/file_io.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		objects/object.h \
		graphicslib.h \
		game_mediator.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		inputlib.h \
		graphic/draw.h \
		timerlib.h \
		strings_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o option_picker.o graphic/option_picker.cpp

dialogs.o: scenes/dialogs.cpp scenes/dialogs.h \
		defines.h \
		file/format/st_common.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		graphicslib.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		inputlib.h \
		graphic/draw.h \
		soundlib.h \
		timerlib.h \
		game.h \
		character/classplayer.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		classmap.h \
		graphic/animation.h \
		class_config.h \
		aux_tools/fps_control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogs.o scenes/dialogs.cpp

file_io.o: file/file_io.cpp logger.h \
		file/file_io.h \
		file/format.h \
		defines.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/convert.h \
		aux_tools/stringutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file_io.o file/file_io.cpp

animation.o: graphic/animation.cpp graphic/animation.h \
		file/format/st_common.h \
		defines.h \
		graphicslib.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		timerlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animation.o graphic/animation.cpp

artificial_inteligence.o: character/artificial_inteligence.cpp logger.h \
		character/artificial_inteligence.h \
		character/character.h \
		file/format/st_hitPoints.h \
		file/format/st_common.h \
		defines.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		graphicslib.h \
		file/format.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		soundlib.h \
		timerlib.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classplayer.h \
		character/classnpc.h \
		classmap.h \
		graphic/animation.h \
		game.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o artificial_inteligence.o character/artificial_inteligence.cpp

key_map.o: options/key_map.cpp options/key_map.h \
		file/format.h \
		defines.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		graphicslib.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		inputlib.h \
		soundlib.h \
		graphic/draw.h \
		timerlib.h \
		graphic/option_picker.h \
		strings_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o key_map.o options/key_map.cpp

draw.o: graphic/draw.cpp graphic/draw.h \
		graphicslib.h \
		defines.h \
		file/format/st_common.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		soundlib.h \
		timerlib.h \
		game.h \
		character/classplayer.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		classmap.h \
		graphic/animation.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h \
		inputlib.h \
		data/datautil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o draw.o graphic/draw.cpp

trajectory_parabola.o: aux_tools/trajectory_parabola.cpp aux_tools/trajectory_parabola.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trajectory_parabola.o aux_tools/trajectory_parabola.cpp

convert.o: file/convert.cpp file/convert.h \
		file/file_io.h \
		file/format.h \
		defines.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o convert.o file/convert.cpp

jump.o: character/movement/jump.cpp character/movement/jump.h \
		defines.h \
		shareddata.h \
		file/file_io.h \
		file/format.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		objects/object.h \
		graphicslib.h \
		game_mediator.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		game.h \
		character/classplayer.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		graphic/draw.h \
		soundlib.h \
		timerlib.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		scenes/game_menu.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		file/fio_scenes.h \
		stage.h \
		classmap.h \
		graphic/animation.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jump.o character/movement/jump.cpp

inertia.o: character/movement/inertia.cpp character/movement/inertia.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inertia.o character/movement/inertia.cpp

fio_scenes.o: file/fio_scenes.cpp file/fio_scenes.h \
		file/v4/file_scene_v4.h \
		defines.h \
		file/format/st_common.h \
		aux_tools/exception_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fio_scenes.o file/fio_scenes.cpp

sceneshow.o: scenes/sceneshow.cpp scenes/sceneshow.h \
		defines.h \
		file/fio_scenes.h \
		file/v4/file_scene_v4.h \
		file/format/st_common.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		soundlib.h \
		shareddata.h \
		file/file_io.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		objects/object.h \
		graphicslib.h \
		game_mediator.h \
		inputlib.h \
		graphic/draw.h \
		timerlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sceneshow.o scenes/sceneshow.cpp

strings_map.o: strings_map.cpp strings_map.h \
		defines.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		file/format/st_common.h \
		shareddata.h \
		file/file_io.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		objects/object.h \
		graphicslib.h \
		game_mediator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o strings_map.o strings_map.cpp

fio_strings.o: file/fio_strings.cpp file/fio_strings.h \
		file/v4/file_strings.h \
		defines.h \
		file/format/st_common.h \
		aux_tools/stringutils.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		shareddata.h \
		file/file_io.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		objects/object.h \
		graphicslib.h \
		game_mediator.h \
		strings_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fio_strings.o file/fio_strings.cpp

stringutils.o: aux_tools/stringutils.cpp aux_tools/stringutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stringutils.o aux_tools/stringutils.cpp

fio_common.o: file/fio_common.cpp file/fio_common.h \
		aux_tools/exception_manager.h \
		defines.h \
		file/v4/file_save_v4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fio_common.o file/fio_common.cpp

game_mediator.o: game_mediator.cpp game_mediator.h \
		file/format.h \
		defines.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		soundlib.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		graphicslib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game_mediator.o game_mediator.cpp

collision_detection.o: collision_detection.cpp collision_detection.h \
		file/format/st_common.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collision_detection.o collision_detection.cpp

gfx_sin_wave.o: graphic/gfx_sin_wave.cpp graphic/gfx_sin_wave.h \
		defines.h \
		graphicslib.h \
		file/format/st_common.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		timerlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gfx_sin_wave.o graphic/gfx_sin_wave.cpp

character_animation.o: character/character_animation.cpp character/character_animation.h \
		defines.h \
		graphicslib.h \
		file/format/st_common.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		timerlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o character_animation.o character/character_animation.cpp

exception_manager.o: aux_tools/exception_manager.cpp aux_tools/exception_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exception_manager.o aux_tools/exception_manager.cpp

game_menu.o: scenes/game_menu.cpp scenes/game_menu.h \
		defines.h \
		graphicslib.h \
		file/format/st_common.h \
		file/format.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		game_mediator.h \
		file/fio_common.h \
		aux_tools/exception_manager.h \
		file/fio_strings.h \
		file/v4/file_strings.h \
		shareddata.h \
		file/file_io.h \
		objects/object.h \
		strings_map.h \
		graphic/option_picker.h \
		options/key_map.h \
		inputlib.h \
		soundlib.h \
		graphic/draw.h \
		game.h \
		character/classplayer.h \
		character/character.h \
		file/format/st_characterState.h \
		file/format/st_teleporter.h \
		file/format/st_projectile.h \
		file/format/st_platform.h \
		projectilelib.h \
		aux_tools/trajectory_parabola.h \
		timerlib.h \
		character/movement/jump.h \
		character/movement/inertia.h \
		character/character_animation.h \
		character/classnpc.h \
		character/artificial_inteligence.h \
		sceneslib.h \
		file/fio_scenes.h \
		stage.h \
		classmap.h \
		graphic/animation.h \
		class_config.h \
		scenes/dialogs.h \
		aux_tools/fps_control.h \
		ports/android/android_game_services.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game_menu.o scenes/game_menu.cpp

android_game_services.o: ports/android/android_game_services.cpp ports/android/android_game_services.h \
		defines.h \
		file/file_io.h \
		file/format.h \
		file/format/st_common.h \
		file/format/st_hitPoints.h \
		file/v4/file_stage_v4.h \
		file/v4/file_map.h \
		file/v4/file_game_v4.h \
		file/v4/file_save_v4.h \
		file/v4/file_config_v4.h \
		file/v4/file_config_old.h \
		file/v4/file_scene_v4.h \
		file/v4/file_anim_block.h \
		file/fio_common.h \
		aux_tools/exception_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o android_game_services.o ports/android/android_game_services.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

